### ISSUE TITLE
Copying more than 10 000 rows

### ISSUE THREAD

**Issue by franckdepicardie** [eltoroit/ETCopyData#38]
Hello,

Another issue which i don't know how to deal with : 

Is there a way to insert more than 10 000 rows at a time or in several step but with all the lookups correctly set ? Currently I have a breakdown after 10000 limit.

For information, I am wanting to insert at the same time more than 10 000 rows because i am trying to embrace the whole update of the hierarchy (in my case, it's the object account).

If i separate the records in different pack, i am affraid that lookups will not be correctly set as some of the good account are already stored in salesforce but with new id ref and other are being retrieved in cache memory of the execution with source id ref...

**Comment by eltoroit** [comment]
I never tested with such a large amount of data because that is not the idea of this plugin, and I am not sure if it will work. Remember that you can always use DataLoader for this test, you may need to add External Ids to help on the matching.

P.S. Do you really need so much data to write your code?
